---

- name: Ensure HAProxy  is installed
  apt: name=haproxy state=latest

- name: Ensure HAProxy is enable
  lineinfile:    #Modulo
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$" #Busca por medio de expresion regular
    line: "ENABLED=1"   #Si no se encuentra, añadira la linea
    state: present  #Obliga a que este preseten la linea

- name: Copy HAProcxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 6644
    validate: haproxy -f %s -c -q
  notify: restart HAProxy

- name: Ensure HAProxy is started and enabled on boot
  service: name=haproxy state=started enabled=yes
  