---

- name: Ensure Apache is installed
  apt: name={{ apache_packages }} state=latest
  #apt: name={{ item }} state=latest 
  #with_items: "{{ apache_packages }}"  --> loop deprecated in ansible 2.11

- name: Enable apache modules
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: link
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache2

- name: Add apache vhost Configuration
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache2 

- name: Add vhost symlink in sites-enabled
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
  notify: restart apache2

- name: Remove default vhost in sites-enabled
  file:
    path: "{{ apache_conf_path }}/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache2