---

- hosts: webserver
  remote_user: "{{ ssh_user }}"
  roles:
    - role: webserver_install
    - role: webserver_run

- hosts: mongodb
  remote_user: "{{ ssh_user }}"
  roles:
    - role: mongodb_install
    - role: mongodb_run