---
# defaults file for roles/php-fpm

php_directory: '/etc/php/7.0'

php_logs_directory: '/var/log/php7-fpm'

php_packages:
  - php7.4
  - libapache2-mod-php7.4
  - php7.4-mysql
  - php7.4-curl
  - php7.4-gd
  - php7.4-intl
  - php-pear
  - php-imagick
  - php7.4-imap
  - php-memcache
  - php7.4-pspell
  - php7.4-sqlite3
  - php7.4-tidy
  - php7.4-xmlrpc
  - php7.4-xsl
  - php7.4-mbstring
  - php7.4-opcache
  - php-apcu
